name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger this workflow when there are pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Run the job on the latest Ubuntu environment

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx (for advanced builds like multi-architecture)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # GitHub secret for Docker username
          password: ${{ secrets.DOCKER_PASSWORD }}  # GitHub secret for Docker password

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t hamzehhatamleh924/myapp:latest .

      # Step 5: Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push hamzehhatamleh924/myapp:latest
